<?php
/***********************************************************************************/
/* WARNING:                                                                        */
/* The wp-config.php file is automatically generated by Flywheel. You will not be  */
/* able to edit this file yourself. Defines needed for plugins can be added to a   */
/* php file in your wp-content/mu-plugins directory. If you need to add defines    */
/* for core WordPress functionality, please contact Flywheel support at            */
/* app.getflywheel.com/help.                                                       */
/***********************************************************************************/

defined('WP_CONTENT_DIR') or define( 'WP_CONTENT_DIR', dirname( __FILE__ ) . '/wp-content' );

define('FLYWHEEL_CONFIG_DIR', dirname(__FILE__) . '/flywheel-config');
define('FLYWHEEL_PLUGIN_DIR', FLYWHEEL_CONFIG_DIR . '/plugins');
define('FLYWHEEL_DEFAULT_PROTOCOL', 'https://');
define('WPMU_PLUGIN_DIR', dirname(__FILE__) . '/wp-content/mu-plugins');
define('WPMU_PLUGIN_URL', '/wp-content/mu-plugins');
define('FS_METHOD', 'direct');
define('WP_POST_REVISIONS',  10);
define('WP_MEMORY_LIMIT', '256M');

define('FW_EVENT_ENABLED', true);
define('FW_HOME_PURGE', false);



/****************************************************************************/
/*                           Domain Configuration                           */
/****************************************************************************/

if ( !(defined('WP_CLI') && WP_CLI) ) {
    define('WP_SITEURL', FLYWHEEL_DEFAULT_PROTOCOL . 'asgmt.mysites.io');
    define('WP_HOME', FLYWHEEL_DEFAULT_PROTOCOL . 'asgmt.mysites.io');
}




/****************************************************************************/
/*                         Database Configuration                           */
/****************************************************************************/
define('DB_NAME', 'db3673999131');
define('DB_USER', 'fw1753715685');
define('DB_PASSWORD', '5pjt53ssOA5MRVwhrnv2AYeWCBmbn8');
define('DB_HOST', '192.168.4.236');

define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');

$table_prefix  = 'wp_1r6bsceqx3_';









/****************************************************************************/
/*                             WordPress Salts                              */
/****************************************************************************/
define('AUTH_KEY',          'sntbUr;!WB{[loTgMS3I,y!r;}y]}[H{,}700gYxRp>a-*1~]a9La8d@XknMTjAt');
define('SECURE_AUTH_KEY',   'b$r|tQ@f*r#Lk&sGWIzAY{?D%tKK[]Hj4sq7Z67FD!Pc.~TiN4%Eac?|^?AuCiw&');
define('LOGGED_IN_KEY',     '4j5o+Nw!QUBIz3iuF2XD6A^}!9$H+^n&n;-,K{RC7.d1!u;/?0AQjY8Y[`QKp*gW');
define('NONCE_KEY',         '_-A2<pN!gufFgb2rqco[xnvWFW9+0Dr&$=[Dy+4D~4kn_Plx?h4cn]Ty,-E!zL^z');
define('AUTH_SALT',         '!EyuNStl#udBZf,OiQ9ebFIwm^vH]|sjAW@6M{p2SPQwCr`,(sEV2a9tCxe%V595');
define('SECURE_AUTH_SALT',  'o/HL72oYzXw.aqAvL{KXz(!1BsJFyraR{BE;^1siZI?Q7<Cw^/x=oPU&X4N?Z_1f');
define('LOGGED_IN_SALT',    'X)cY9b04d*Y7b#~147s,_f|-;p<dhC~&%%^u8[goL+Z3-DHq&hYR<7L@5gkIfKzl');
define('NONCE_SALT',        'MHY>r9pv(hi[sIP~kfyaB+pbW@[Grq!?{4?*q5`%JzN%xk5)zF_ANonOGH{|~h.1');


/****************************************************************************/
/*                        General WordPress Settings                        */
/****************************************************************************/


define('WP_DEBUG', true);

define('WP_CACHE', false);



/****************************************************************************/
/*                          Plugin Configuration                            */
/****************************************************************************/
define( 'FW_WHITE_LABEL', true );




/****************************************************************************/
/*                              Custom Content                              */
/****************************************************************************/
define( 'WP_DEBUG_DISPLAY', false );


/****************************************************************************/
/*                     Disable WordPress Auto-updates                       */
/*           http://getflywheel.com/flywheel-wordpress-3-7/                 */
/****************************************************************************/
define('WP_AUTO_UPDATE_CORE', false);

/****************************************************************************/
/*                    Flywheel NextGen Gallery Support                      */
/****************************************************************************/
define('NGG_GALLERY_ROOT_TYPE', 'content');


if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/.wordpress/');

if ( !empty( $_SERVER['HTTP_FASTLY_SSL'] ) || ( !empty( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && ( $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' ) ) )
	$_SERVER['HTTPS']='on';



require_once(ABSPATH . 'wp-settings.php');
