<?php
require __DIR__.'/vendor/autoload.php';

use Spipu\Html2Pdf\Html2Pdf;

//if (!isset($_GET['data'])) return;


//$data = urldecode($_POST['data']);

$styles = '<style type="text/Css">#templates .badge{width:377.95px;min-height:566.93px;display:inline-block;font-family:arial;line-height:1.4;color:#000;text-align:center;margin:20px;background:#fff;position:relative}#templates .badge .user-role{background:red;height:53.6px;font-size:24pt;display:flex;align-items:center;justify-content:center}#templates .badge .user-name,#templates .badge .user-surname{font-family:arial-black;font-size:22pt;text-transform:uppercase;min-height:40px}#templates .badge .user-company{font-size:15pt;min-height:48px;line-height:2;display:block}#templates .badge .country{font-size:19pt;text-transform:uppercase;min-height:35px}#templates .badge .user-avatar{width:127px;height:127px;display:block;margin:0 auto}#templates .badge .user-avatar img{width:100%;height:100%;object-fit:cover;object-position:top}#templates .badge .top-badge{display:flex;justify-content:space-between;margin:6px 6px 28px}#templates .badge .top-badge .left img{max-width:203px}#templates .badge .top-badge .right img{max-width:78px}#templates .badge .qr-code-container{position:relative;margin:8px 0}#templates .badge .qr-code{height:122px;width:122px;display:flex;align-items:center;justify-content:center;margin:0 auto}#templates .badge .qr-code img{width:100%;height:100%;image-rendering:pixelated}#templates .badge .reg-id{position:absolute;right:31px;bottom:0}</style><div class="badge"><div class="top-badge"><div class="left"><img src="http://aippi.local/wp-content/plugins/badges/assets/images/event.png"></div><div class="right"><img src="http://aippi.local/wp-content/plugins/badges/assets/images/aippi.png"></div></div><div class="user-avatar"><img src="http://aippi.local/wp-content/uploads/congress_2018/7686_original_cropped.jpg"></div><div class="user-name">Vladimir</div><div class="user-surname">ANOHIN</div><div class="user-company">Agency TRIA ROBIT</div><div class="country">Latvia</div><div class="qr-code-container"><div class="qr-code"><img src="http://aippi.local/wp-content/plugins/badges/inc/generate.php?secret_key=msdbfsldf;l922lkn3lk4n4n&amp;user_avatar=http://aippi.org/wp-content/uploads/member_photos/7686_member_thumb.jpg&amp;data=data%5Bid%5D=3353&amp;data%5Bcong_reg_id%5D=&amp;data%5Bname%5D=Vladimir&amp;data%5Bsurname%5D=ANOHIN&amp;data%5Bcountry%5D=Latvia&amp;data%5Bcompany%5D=Agency+TRIA+ROBIT&amp;data%5Bbadge_color%5D=blue&amp;data%5Bbadge_title%5D=Member&amp;data%5Buser_id%5D=7686&amp;data%5Bcongress_year%5D=2018"></div><div class="reg-id">Reg ID 3353</div></div><div class="user-role" style="background:blue;">Member</div></div>';